[2023-08-28T19:45:39.311+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-28T19:45:39.312+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push'
[2023-08-28T19:45:39.419+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-28T19:45:39.425+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push'
[2023-08-28T19:45:39.585+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-27T00:10:00+00:00 [queued]>
[2023-08-28T19:45:39.596+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-27T00:10:00+00:00 [queued]>
[2023-08-28T19:45:39.597+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-28T19:45:39.661+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_push> on 2023-08-27 00:10:00+00:00
[2023-08-28T19:45:39.667+0000] {standard_task_runner.py:57} INFO - Started process 83 to run task
[2023-08-28T19:45:39.671+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_with_xcom', 'bash_push', 'scheduled__2023-08-27T00:10:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_with_xcom.py', '--cfg-path', '/tmp/tmp2wdobmr8']
[2023-08-28T19:45:39.674+0000] {standard_task_runner.py:85} INFO - Job 99: Subtask bash_push
[2023-08-28T19:45:39.765+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-28T19:45:39.765+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_push'
[2023-08-28T19:45:39.768+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-27T00:10:00+00:00 [running]> on host 07fcf706bef2
[2023-08-28T19:45:40.023+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_with_xcom' AIRFLOW_CTX_TASK_ID='bash_push' AIRFLOW_CTX_EXECUTION_DATE='2023-08-27T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-27T00:10:00+00:00'
[2023-08-28T19:45:40.026+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-28T19:45:40.027+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo START && echo XCOM_PUSHEDNone && echo COMPLETE']
[2023-08-28T19:45:40.037+0000] {subprocess.py:86} INFO - Output:
[2023-08-28T19:45:40.038+0000] {subprocess.py:93} INFO - START
[2023-08-28T19:45:40.039+0000] {subprocess.py:93} INFO - XCOM_PUSHEDNone
[2023-08-28T19:45:40.039+0000] {subprocess.py:93} INFO - COMPLETE
[2023-08-28T19:45:40.040+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-28T19:45:40.178+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_bash_with_xcom, task_id=bash_push, execution_date=20230827T001000, start_date=20230828T194539, end_date=20230828T194540
[2023-08-28T19:45:40.245+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-28T19:45:40.268+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
