[2023-08-31T04:07:58.445+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info permission to 509
[2023-08-31T04:07:58.447+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info'
[2023-08-31T04:07:58.494+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info permission to 509
[2023-08-31T04:07:58.496+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info'
[2023-08-31T04:07:58.649+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_simple_http_operator.baywheels_gbfs_info manual__2023-08-31T04:07:56.778467+00:00 [queued]>
[2023-08-31T04:07:58.659+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_simple_http_operator.baywheels_gbfs_info manual__2023-08-31T04:07:56.778467+00:00 [queued]>
[2023-08-31T04:07:58.660+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T04:07:58.693+0000] {taskinstance.py:1327} INFO - Executing <Task(SimpleHttpOperator): baywheels_gbfs_info> on 2023-08-31 04:07:56.778467+00:00
[2023-08-31T04:07:58.765+0000] {standard_task_runner.py:57} INFO - Started process 1845 to run task
[2023-08-31T04:07:58.769+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_simple_http_operator', 'baywheels_gbfs_info', 'manual__2023-08-31T04:07:56.778467+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/dags_simple_http_operator.py', '--cfg-path', '/tmp/tmpxp0wcf2y']
[2023-08-31T04:07:58.772+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask baywheels_gbfs_info
[2023-08-31T04:07:58.864+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info permission to 509
[2023-08-31T04:07:58.865+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_simple_http_operator/run_id=manual__2023-08-31T04:07:56.778467+00:00/task_id=baywheels_gbfs_info'
[2023-08-31T04:07:58.868+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_simple_http_operator.baywheels_gbfs_info manual__2023-08-31T04:07:56.778467+00:00 [running]> on host 07fcf706bef2
[2023-08-31T04:07:59.027+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_simple_http_operator' AIRFLOW_CTX_TASK_ID='baywheels_gbfs_info' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T04:07:56.778467+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T04:07:56.778467+00:00'
[2023-08-31T04:07:59.028+0000] {http.py:123} INFO - Calling HTTP method
[2023-08-31T04:07:59.036+0000] {base.py:73} INFO - Using connection ID 'gbfs.baywheels.com' for task execution.
[2023-08-31T04:07:59.093+0000] {http.py:181} ERROR - HTTP error: Bad Request
[2023-08-31T04:07:59.094+0000] {http.py:182} ERROR - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>400 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: pouEXDtE3efUwrERjySsqqK6aexdmdgwKfKWyjOxGZXjCELhtebnLQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
[2023-08-31T04:07:59.103+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 179, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://gbfs.baywheels.com:443/2.3/gbfs.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 125, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 169, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 222, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 183, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 400:Bad Request
[2023-08-31T04:07:59.109+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dags_simple_http_operator, task_id=baywheels_gbfs_info, execution_date=20230831T040756, start_date=20230831T040758, end_date=20230831T040759
[2023-08-31T04:07:59.138+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 208 for task baywheels_gbfs_info (400:Bad Request; 1845)
[2023-08-31T04:07:59.181+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-31T04:07:59.205+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
