[2023-08-30T20:45:49.216+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-30T20:45:49.217+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull'
[2023-08-30T20:45:49.283+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-30T20:45:49.285+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull'
[2023-08-30T20:45:49.430+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-29T00:10:00+00:00 [queued]>
[2023-08-30T20:45:49.439+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-29T00:10:00+00:00 [queued]>
[2023-08-30T20:45:49.439+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T20:45:49.491+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_pull> on 2023-08-29 00:10:00+00:00
[2023-08-30T20:45:49.496+0000] {standard_task_runner.py:57} INFO - Started process 98 to run task
[2023-08-30T20:45:49.498+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_with_xcom', 'bash_pull', 'scheduled__2023-08-29T00:10:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_with_xcom.py', '--cfg-path', '/tmp/tmpagx5b_m1']
[2023-08-30T20:45:49.500+0000] {standard_task_runner.py:85} INFO - Job 188: Subtask bash_pull
[2023-08-30T20:45:49.558+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-30T20:45:49.558+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_pull'
[2023-08-30T20:45:49.561+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-29T00:10:00+00:00 [running]> on host 07fcf706bef2
[2023-08-30T20:45:49.731+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_with_xcom' AIRFLOW_CTX_TASK_ID='bash_pull' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T00:10:00+00:00'
[2023-08-30T20:45:49.733+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:45:49.734+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo $PUSHED_VALUE && echo $RETURN_VALUE']
[2023-08-30T20:45:49.742+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:45:49.743+0000] {subprocess.py:93} INFO - first_bash_message
[2023-08-30T20:45:49.744+0000] {subprocess.py:93} INFO - COMPLETE
[2023-08-30T20:45:49.744+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T20:45:49.754+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_bash_with_xcom, task_id=bash_pull, execution_date=20230829T001000, start_date=20230830T204549, end_date=20230830T204549
[2023-08-30T20:45:49.790+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-30T20:45:49.806+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
