[2023-08-29T00:52:11.500+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-29T00:52:11.501+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull'
[2023-08-29T00:52:11.550+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-29T00:52:11.551+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull'
[2023-08-29T00:52:11.715+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-28T00:10:00+00:00 [queued]>
[2023-08-29T00:52:11.724+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-28T00:10:00+00:00 [queued]>
[2023-08-29T00:52:11.725+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-29T00:52:11.766+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_pull> on 2023-08-28 00:10:00+00:00
[2023-08-29T00:52:11.771+0000] {standard_task_runner.py:57} INFO - Started process 73 to run task
[2023-08-29T00:52:11.775+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_with_xcom', 'bash_pull', 'scheduled__2023-08-28T00:10:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_with_xcom.py', '--cfg-path', '/tmp/tmp72ef7njz']
[2023-08-29T00:52:11.778+0000] {standard_task_runner.py:85} INFO - Job 127: Subtask bash_pull
[2023-08-29T00:52:11.878+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-29T00:52:11.879+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-28T00:10:00+00:00/task_id=bash_pull'
[2023-08-29T00:52:11.882+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-28T00:10:00+00:00 [running]> on host 07fcf706bef2
[2023-08-29T00:52:12.116+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_with_xcom' AIRFLOW_CTX_TASK_ID='bash_pull' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T00:10:00+00:00'
[2023-08-29T00:52:12.118+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-29T00:52:12.119+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo $PUSHED_VALUE && echo $RETURN_VALUE']
[2023-08-29T00:52:12.129+0000] {subprocess.py:86} INFO - Output:
[2023-08-29T00:52:12.130+0000] {subprocess.py:93} INFO - first_bash_message
[2023-08-29T00:52:12.131+0000] {subprocess.py:93} INFO - COMPLETE
[2023-08-29T00:52:12.131+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-29T00:52:12.143+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_bash_with_xcom, task_id=bash_pull, execution_date=20230828T001000, start_date=20230829T005211, end_date=20230829T005212
[2023-08-29T00:52:12.228+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-29T00:52:12.245+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
