[2023-08-31T09:30:01.387+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task permission to 509
[2023-08-31T09:30:01.389+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task'
[2023-08-31T09:30:01.440+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task permission to 509
[2023-08-31T09:30:01.449+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task'
[2023-08-31T09:30:01.738+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_trigger_dag_run_operator.start_task scheduled__2023-08-30T09:30:00+00:00 [queued]>
[2023-08-31T09:30:01.748+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_trigger_dag_run_operator.start_task scheduled__2023-08-30T09:30:00+00:00 [queued]>
[2023-08-31T09:30:01.749+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T09:30:01.783+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): start_task> on 2023-08-30 09:30:00+00:00
[2023-08-31T09:30:01.789+0000] {standard_task_runner.py:57} INFO - Started process 6517 to run task
[2023-08-31T09:30:01.792+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_trigger_dag_run_operator', 'start_task', 'scheduled__2023-08-30T09:30:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/dags_trigger_dag_run_operator.py', '--cfg-path', '/tmp/tmpenojlkvg']
[2023-08-31T09:30:01.794+0000] {standard_task_runner.py:85} INFO - Job 224: Subtask start_task
[2023-08-31T09:30:01.878+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task permission to 509
[2023-08-31T09:30:01.879+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_trigger_dag_run_operator/run_id=scheduled__2023-08-30T09:30:00+00:00/task_id=start_task'
[2023-08-31T09:30:01.882+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_trigger_dag_run_operator.start_task scheduled__2023-08-30T09:30:00+00:00 [running]> on host 07fcf706bef2
[2023-08-31T09:30:02.053+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_trigger_dag_run_operator' AIRFLOW_CTX_TASK_ID='start_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T09:30:00+00:00'
[2023-08-31T09:30:02.056+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-31T09:30:02.057+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "start!"']
[2023-08-31T09:30:02.068+0000] {subprocess.py:86} INFO - Output:
[2023-08-31T09:30:02.070+0000] {subprocess.py:93} INFO - start!
[2023-08-31T09:30:02.071+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-31T09:30:02.128+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_trigger_dag_run_operator, task_id=start_task, execution_date=20230830T093000, start_date=20230831T093001, end_date=20230831T093002
[2023-08-31T09:30:02.205+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T09:30:02.228+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
